
import java.math.BigDecimal;
import java.util.List;
import obj.Ficha;
import org.hibernate.Session;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author nicol
 */
public class CartaDeTiro extends javax.swing.JFrame {
 
    /**
     * Creates new form CartaDeTiro
     */
    private EnJuego juego;
    private String dniJugador;
    private String equipo;
    private EnJuego partido;
    public CartaDeTiro() {
        initComponents();
        setSize(443, 366);
        setLocationRelativeTo(null);
        setTitle("carta de tiro ");
    }

    public void setEnJuego(EnJuego juego){
        this.juego = juego;
    }
    public void setDni(String dni){
        dniJugador= dni;
    }
    public void setEquipo(String equipo){
        this.equipo = equipo;
    }
    public void setPartido(EnJuego partido){
        this.partido=partido;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        aIn3Btn = new javax.swing.JButton();
        aOut3Btn = new javax.swing.JButton();
        bIn3btn = new javax.swing.JButton();
        bOut3Btn = new javax.swing.JButton();
        cIn3Btn = new javax.swing.JButton();
        cOut3Btn = new javax.swing.JButton();
        dIn3Btn = new javax.swing.JButton();
        dOut3Btn = new javax.swing.JButton();
        eIn3Btn = new javax.swing.JButton();
        eOut3Btn = new javax.swing.JButton();
        aIn2Btn = new javax.swing.JButton();
        aOut2Btn = new javax.swing.JButton();
        bIn2Btn = new javax.swing.JButton();
        bOut2Btn = new javax.swing.JButton();
        cInOutBtn = new javax.swing.JButton();
        cOut2btn = new javax.swing.JButton();
        eOut2Btn = new javax.swing.JButton();
        eIn2Btn = new javax.swing.JButton();
        dOut2Btn = new javax.swing.JButton();
        d2InBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        libreOut = new javax.swing.JButton();
        libreIn = new javax.swing.JButton();
        f_inBtn = new javax.swing.JButton();
        f_OutBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ahorase.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        aIn3Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tick.png"))); // NOI18N
        aIn3Btn.setBorderPainted(false);
        aIn3Btn.setContentAreaFilled(false);
        aIn3Btn.setFocusPainted(false);
        aIn3Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aIn3BtnActionPerformed(evt);
            }
        });
        getContentPane().add(aIn3Btn);
        aIn3Btn.setBounds(10, 10, 30, 30);

        aOut3Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cruz.png"))); // NOI18N
        aOut3Btn.setContentAreaFilled(false);
        aOut3Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aOut3BtnActionPerformed(evt);
            }
        });
        getContentPane().add(aOut3Btn);
        aOut3Btn.setBounds(10, 60, 30, 30);

        bIn3btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tick.png"))); // NOI18N
        bIn3btn.setContentAreaFilled(false);
        bIn3btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bIn3btnActionPerformed(evt);
            }
        });
        getContentPane().add(bIn3btn);
        bIn3btn.setBounds(30, 170, 30, 30);

        bOut3Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cruz.png"))); // NOI18N
        bOut3Btn.setContentAreaFilled(false);
        bOut3Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOut3BtnActionPerformed(evt);
            }
        });
        getContentPane().add(bOut3Btn);
        bOut3Btn.setBounds(40, 190, 70, 50);

        cIn3Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tick.png"))); // NOI18N
        cIn3Btn.setContentAreaFilled(false);
        cIn3Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cIn3BtnActionPerformed(evt);
            }
        });
        getContentPane().add(cIn3Btn);
        cIn3Btn.setBounds(170, 250, 40, 41);

        cOut3Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cruz.png"))); // NOI18N
        cOut3Btn.setContentAreaFilled(false);
        cOut3Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cOut3BtnActionPerformed(evt);
            }
        });
        getContentPane().add(cOut3Btn);
        cOut3Btn.setBounds(240, 250, 40, 30);

        dIn3Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tick.png"))); // NOI18N
        dIn3Btn.setContentAreaFilled(false);
        dIn3Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dIn3BtnActionPerformed(evt);
            }
        });
        getContentPane().add(dIn3Btn);
        dIn3Btn.setBounds(350, 210, 30, 41);

        dOut3Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cruz.png"))); // NOI18N
        dOut3Btn.setContentAreaFilled(false);
        dOut3Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dOut3BtnActionPerformed(evt);
            }
        });
        getContentPane().add(dOut3Btn);
        dOut3Btn.setBounds(380, 170, 30, 41);

        eIn3Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tick.png"))); // NOI18N
        eIn3Btn.setContentAreaFilled(false);
        eIn3Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eIn3BtnActionPerformed(evt);
            }
        });
        getContentPane().add(eIn3Btn);
        eIn3Btn.setBounds(400, 60, 30, 41);

        eOut3Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cruz.png"))); // NOI18N
        eOut3Btn.setContentAreaFilled(false);
        eOut3Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eOut3BtnActionPerformed(evt);
            }
        });
        getContentPane().add(eOut3Btn);
        eOut3Btn.setBounds(400, 20, 40, 41);

        aIn2Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tick.png"))); // NOI18N
        aIn2Btn.setBorderPainted(false);
        aIn2Btn.setContentAreaFilled(false);
        aIn2Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aIn2BtnActionPerformed(evt);
            }
        });
        getContentPane().add(aIn2Btn);
        aIn2Btn.setBounds(60, 10, 65, 41);

        aOut2Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cruz.png"))); // NOI18N
        aOut2Btn.setContentAreaFilled(false);
        aOut2Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aOut2BtnActionPerformed(evt);
            }
        });
        getContentPane().add(aOut2Btn);
        aOut2Btn.setBounds(70, 50, 65, 41);

        bIn2Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tick.png"))); // NOI18N
        bIn2Btn.setContentAreaFilled(false);
        bIn2Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bIn2BtnActionPerformed(evt);
            }
        });
        getContentPane().add(bIn2Btn);
        bIn2Btn.setBounds(60, 110, 65, 41);

        bOut2Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cruz.png"))); // NOI18N
        bOut2Btn.setContentAreaFilled(false);
        bOut2Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOut2BtnActionPerformed(evt);
            }
        });
        getContentPane().add(bOut2Btn);
        bOut2Btn.setBounds(90, 140, 65, 41);

        cInOutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tick.png"))); // NOI18N
        cInOutBtn.setContentAreaFilled(false);
        cInOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cInOutBtnActionPerformed(evt);
            }
        });
        getContentPane().add(cInOutBtn);
        cInOutBtn.setBounds(150, 190, 79, 30);

        cOut2btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cruz.png"))); // NOI18N
        cOut2btn.setContentAreaFilled(false);
        cOut2btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cOut2btnActionPerformed(evt);
            }
        });
        getContentPane().add(cOut2btn);
        cOut2btn.setBounds(220, 190, 65, 41);

        eOut2Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cruz.png"))); // NOI18N
        eOut2Btn.setText("\n");
        eOut2Btn.setContentAreaFilled(false);
        eOut2Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eOut2BtnActionPerformed(evt);
            }
        });
        getContentPane().add(eOut2Btn);
        eOut2Btn.setBounds(330, 20, 69, 41);

        eIn2Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tick.png"))); // NOI18N
        eIn2Btn.setContentAreaFilled(false);
        eIn2Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eIn2BtnActionPerformed(evt);
            }
        });
        getContentPane().add(eIn2Btn);
        eIn2Btn.setBounds(330, 60, 65, 41);

        dOut2Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cruz.png"))); // NOI18N
        dOut2Btn.setContentAreaFilled(false);
        dOut2Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dOut2BtnActionPerformed(evt);
            }
        });
        getContentPane().add(dOut2Btn);
        dOut2Btn.setBounds(310, 140, 65, 30);

        d2InBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tick.png"))); // NOI18N
        d2InBtn.setContentAreaFilled(false);
        d2InBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d2InBtnActionPerformed(evt);
            }
        });
        getContentPane().add(d2InBtn);
        d2InBtn.setBounds(290, 170, 65, 41);

        jLabel4.setText("libres");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(210, 120, 31, 20);

        libreOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cruz.png"))); // NOI18N
        libreOut.setContentAreaFilled(false);
        libreOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                libreOutActionPerformed(evt);
            }
        });
        getContentPane().add(libreOut);
        libreOut.setBounds(180, 140, 40, 30);

        libreIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tick.png"))); // NOI18N
        libreIn.setContentAreaFilled(false);
        libreIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                libreInActionPerformed(evt);
            }
        });
        getContentPane().add(libreIn);
        libreIn.setBounds(220, 141, 40, 30);

        f_inBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tick.png"))); // NOI18N
        f_inBtn.setContentAreaFilled(false);
        f_inBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f_inBtnActionPerformed(evt);
            }
        });
        getContentPane().add(f_inBtn);
        f_inBtn.setBounds(160, 30, 65, 41);

        f_OutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cruz.png"))); // NOI18N
        f_OutBtn.setContentAreaFilled(false);
        f_OutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f_OutBtnActionPerformed(evt);
            }
        });
        getContentPane().add(f_OutBtn);
        f_OutBtn.setBounds(220, 40, 65, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ahorase.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 440, 360);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aIn3BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aIn3BtnActionPerformed
        Session s = NewHibernateUtil.getSessionFactory().openSession();
        s.beginTransaction();
        BigDecimal tres = new BigDecimal(3);
        List list = juego.existeFicha(dniJugador);
        if (!(list.isEmpty())){
             Ficha f =(Ficha) list.get(0);
             f.setPuntos(f.getPuntos().add(tres));
             BigDecimal Valor1 = new BigDecimal(1);//creo un Big decimal que vale 1 para sumarle 1 a las asistencias existentes
             f.setInA3(f.getInA3().add(Valor1)); 
             s.update(f);
             s.getTransaction().commit();
        }
         else{
                Ficha f = juego.creaFicha(dniJugador,equipo);
                f.setInA3(BigDecimal.ONE);
                f.setPuntos(tres);
                s.save(f);
                s.getTransaction().commit();     
         } 
        s.close();
        SumarPuntos(3);
        this.setVisible(false);
    }//GEN-LAST:event_aIn3BtnActionPerformed

    private void aOut3BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aOut3BtnActionPerformed
        Session s = NewHibernateUtil.getSessionFactory().openSession();
        s.beginTransaction();
        List list = juego.existeFicha(dniJugador);
        if (!(list.isEmpty())){
             Ficha f =(Ficha) list.get(0);
             BigDecimal Valor1 = new BigDecimal(1);//creo un Big decimal que vale 1 para sumarle 1 a las asistencias existentes
             f.setOutA3(f.getOutA3().add(Valor1)); 
             s.update(f);
             s.getTransaction().commit();
        }
         else{
                Ficha f = juego.creaFicha(dniJugador,equipo);
                f.setOutA3(BigDecimal.ONE);
                s.save(f);
                s.getTransaction().commit();     
         } 
        s.close();
        this.setVisible(false);
    }//GEN-LAST:event_aOut3BtnActionPerformed

    private void eOut3BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eOut3BtnActionPerformed
        Session s = NewHibernateUtil.getSessionFactory().openSession();
        s.beginTransaction();
        List list = juego.existeFicha(dniJugador);
        if (!(list.isEmpty())){
             Ficha f =(Ficha) list.get(0);
             BigDecimal Valor1 = new BigDecimal(1);//creo un Big decimal que vale 1 para sumarle 1 a las asistencias existentes
             f.setOutE3(f.getOutE3().add(Valor1)); 
             s.update(f);
             s.getTransaction().commit();
        }
         else{
                Ficha f = juego.creaFicha(dniJugador,equipo);
                f.setOutE3(BigDecimal.ONE);
                s.save(f);
                s.getTransaction().commit();     
         } 
        s.close();
        this.setVisible(false);
    }//GEN-LAST:event_eOut3BtnActionPerformed

    private void bIn3btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bIn3btnActionPerformed
        Session s = NewHibernateUtil.getSessionFactory().openSession();
        s.beginTransaction();
        BigDecimal tres = new BigDecimal(3);
        List list = juego.existeFicha(dniJugador);
        if (!(list.isEmpty())){
             Ficha f =(Ficha) list.get(0);
             f.setPuntos(f.getPuntos().add(tres));
             BigDecimal Valor1 = new BigDecimal(1);//creo un Big decimal que vale 1 para sumarle 1 a las asistencias existentes
             f.setInB3(f.getInB3().add(Valor1)); 
             s.update(f);
             s.getTransaction().commit();
        }
         else{
                Ficha f = juego.creaFicha(dniJugador,equipo);
                f.setInB3(BigDecimal.ONE);
                f.setPuntos(tres);
                s.save(f);
                s.getTransaction().commit();     
         } 
        s.close();
        SumarPuntos(3);
        this.setVisible(false);
    }//GEN-LAST:event_bIn3btnActionPerformed

    private void cIn3BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cIn3BtnActionPerformed
        // TODO add your handling code here:
           Session s = NewHibernateUtil.getSessionFactory().openSession();
        s.beginTransaction();
        BigDecimal tres = new BigDecimal(3);
        List list = juego.existeFicha(dniJugador);
        if (!(list.isEmpty())){
             Ficha f =(Ficha) list.get(0);
             f.setPuntos(f.getPuntos().add(tres));
             BigDecimal Valor1 = new BigDecimal(1);//creo un Big decimal que vale 1 para sumarle 1 a las asistencias existentes
             f.setInC3(f.getInC3().add(Valor1)); 
             s.update(f);
             s.getTransaction().commit();
        }
         else{
                Ficha f = juego.creaFicha(dniJugador,equipo);
                f.setInC3(BigDecimal.ONE);
                f.setPuntos(tres);
                s.save(f);
                s.getTransaction().commit();     
         } 
        s.close();
        SumarPuntos(3);
        this.setVisible(false);
    }//GEN-LAST:event_cIn3BtnActionPerformed

    private void dIn3BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dIn3BtnActionPerformed
        // TODO add your handling code here:}
        Session s = NewHibernateUtil.getSessionFactory().openSession();
        s.beginTransaction();
        BigDecimal tres = new BigDecimal(3);
        List list = juego.existeFicha(dniJugador);
        if (!(list.isEmpty())){
             Ficha f =(Ficha) list.get(0);
             f.setPuntos(f.getPuntos().add(tres));
             BigDecimal Valor1 = new BigDecimal(1);//creo un Big decimal que vale 1 para sumarle 1 a las asistencias existentes
             f.setInD3(f.getInD3().add(Valor1)); 
             s.update(f);
             s.getTransaction().commit();
        }
         else{
                Ficha f = juego.creaFicha(dniJugador,equipo);
                f.setInD3(BigDecimal.ONE);
                f.setPuntos(tres);
                s.save(f);
                s.getTransaction().commit();     
         } 
        s.close();
        SumarPuntos(3);
        this.setVisible(false);
    }//GEN-LAST:event_dIn3BtnActionPerformed

    private void eIn3BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eIn3BtnActionPerformed
        // TODO add your handling code here:
          Session s = NewHibernateUtil.getSessionFactory().openSession();
        s.beginTransaction();
        BigDecimal tres = new BigDecimal(3);
        List list = juego.existeFicha(dniJugador);
        if (!(list.isEmpty())){
             Ficha f =(Ficha) list.get(0);
             f.setPuntos(f.getPuntos().add(tres));
             BigDecimal Valor1 = new BigDecimal(1);//creo un Big decimal que vale 1 para sumarle 1 a las asistencias existentes
             f.setInE3(f.getInE3().add(Valor1)); 
             s.update(f);
             s.getTransaction().commit();
        }
         else{
                Ficha f = juego.creaFicha(dniJugador,equipo);
                f.setInE3(BigDecimal.ONE);
                f.setPuntos(tres);
                s.save(f);
                s.getTransaction().commit();     
         } 
        s.close();
        SumarPuntos(3);
        this.setVisible(false);
    }//GEN-LAST:event_eIn3BtnActionPerformed

    private void bOut3BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOut3BtnActionPerformed
        Session s = NewHibernateUtil.getSessionFactory().openSession();
        s.beginTransaction();
        List list = juego.existeFicha(dniJugador);
        if (!(list.isEmpty())){
             Ficha f =(Ficha) list.get(0);
             BigDecimal Valor1 = new BigDecimal(1);//creo un Big decimal que vale 1 para sumarle 1 a las asistencias existentes
             f.setOutB3(f.getOutB3().add(Valor1)); 
             s.update(f);
             s.getTransaction().commit();
        }
         else{
                Ficha f = juego.creaFicha(dniJugador,equipo);
                f.setOutB3(BigDecimal.ONE);
                s.save(f);
                s.getTransaction().commit();     
         } 
        s.close(); 
        this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_bOut3BtnActionPerformed

    private void cOut3BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cOut3BtnActionPerformed
       Session s = NewHibernateUtil.getSessionFactory().openSession();
        s.beginTransaction();
        List list = juego.existeFicha(dniJugador);
        if (!(list.isEmpty())){
             Ficha f =(Ficha) list.get(0);
             BigDecimal Valor1 = new BigDecimal(1);//creo un Big decimal que vale 1 para sumarle 1 a las asistencias existentes
             f.setOutC3(f.getOutC3().add(Valor1)); 
             s.update(f);
             s.getTransaction().commit();
        }
         else{
                Ficha f = juego.creaFicha(dniJugador,equipo);
                f.setOutC3(BigDecimal.ONE);
                s.save(f);
                s.getTransaction().commit();     
         } 
        s.close();
        this.setVisible(false);
    }//GEN-LAST:event_cOut3BtnActionPerformed

    private void dOut3BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dOut3BtnActionPerformed
        Session s = NewHibernateUtil.getSessionFactory().openSession();
        s.beginTransaction();
        List list = juego.existeFicha(dniJugador);
        if (!(list.isEmpty())){
             Ficha f =(Ficha) list.get(0);
             BigDecimal Valor1 = new BigDecimal(1);//creo un Big decimal que vale 1 para sumarle 1 a las asistencias existentes
             f.setOutD3(f.getOutD3().add(Valor1)); 
             s.update(f);
             s.getTransaction().commit();
        }
         else{
                Ficha f = juego.creaFicha(dniJugador,equipo);
                f.setOutD3(BigDecimal.ONE);
                s.save(f);
                s.getTransaction().commit();     
         } 
        s.close();
        this.setVisible(false);
    }//GEN-LAST:event_dOut3BtnActionPerformed

    private void bOut2BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOut2BtnActionPerformed
        // TODO add your handling code here:
        Session s = NewHibernateUtil.getSessionFactory().openSession();
        s.beginTransaction();
        List list = juego.existeFicha(dniJugador);
        if (!(list.isEmpty())){
             Ficha f =(Ficha) list.get(0);
             BigDecimal Valor1 = new BigDecimal(1);//creo un Big decimal que vale 1 para sumarle 1 a las asistencias existentes
             f.setOutB2(f.getOutB2().add(Valor1)); 
             s.update(f);
             s.getTransaction().commit();
        }
         else{
                Ficha f = juego.creaFicha(dniJugador,equipo);
                f.setOutB2(BigDecimal.ONE);
                s.save(f);
                s.getTransaction().commit();     
         } 
        s.close(); 
        this.setVisible(false);
    }//GEN-LAST:event_bOut2BtnActionPerformed

    private void eIn2BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eIn2BtnActionPerformed
        // TODO add your handling code here:
          Session s = NewHibernateUtil.getSessionFactory().openSession();
        s.beginTransaction();
        BigDecimal tres = new BigDecimal(2);
        List list = juego.existeFicha(dniJugador);
        if (!(list.isEmpty())){
             Ficha f =(Ficha) list.get(0);
             f.setPuntos(f.getPuntos().add(tres));
             BigDecimal Valor1 = new BigDecimal(1);//creo un Big decimal que vale 1 para sumarle 1 a las asistencias existentes
             f.setInE2(f.getInE2().add(Valor1)); 
             s.update(f);
             s.getTransaction().commit();
        }
         else{
                Ficha f = juego.creaFicha(dniJugador,equipo);
                f.setInE2(BigDecimal.ONE);
                f.setPuntos(tres);
                s.save(f);
                s.getTransaction().commit();     
         } 
        s.close();
        SumarPuntos(2);
        this.setVisible(false);
    }//GEN-LAST:event_eIn2BtnActionPerformed

    private void eOut2BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eOut2BtnActionPerformed
        // TODO add your handling code here:
         Session s = NewHibernateUtil.getSessionFactory().openSession();
        s.beginTransaction();
        List list = juego.existeFicha(dniJugador);
        if (!(list.isEmpty())){
             Ficha f =(Ficha) list.get(0);
             BigDecimal Valor1 = new BigDecimal(1);//creo un Big decimal que vale 1 para sumarle 1 a las asistencias existentes
             f.setOutE2(f.getOutE2().add(Valor1)); 
             s.update(f);
             s.getTransaction().commit();
        }
         else{
                Ficha f = juego.creaFicha(dniJugador,equipo);
                f.setOutE2(BigDecimal.ONE);
                s.save(f);
                s.getTransaction().commit();     
         } 
        s.close();
        this.setVisible(false);
    }//GEN-LAST:event_eOut2BtnActionPerformed

    private void dOut2BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dOut2BtnActionPerformed
        // TODO add your handling code here:
         Session s = NewHibernateUtil.getSessionFactory().openSession();
        s.beginTransaction();
        List list = juego.existeFicha(dniJugador);
        if (!(list.isEmpty())){
             Ficha f =(Ficha) list.get(0);
             BigDecimal Valor1 = new BigDecimal(1);//creo un Big decimal que vale 1 para sumarle 1 a las asistencias existentes
             f.setOutD2(f.getOutD2().add(Valor1)); 
             s.update(f);
             s.getTransaction().commit();
        }
         else{
                Ficha f = juego.creaFicha(dniJugador,equipo);
                f.setOutD2(BigDecimal.ONE);
                s.save(f);
                s.getTransaction().commit();     
         } 
        s.close();
        this.setVisible(false);
    }//GEN-LAST:event_dOut2BtnActionPerformed

    private void aIn2BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aIn2BtnActionPerformed
        // TODO add your handling code here:
        Session s = NewHibernateUtil.getSessionFactory().openSession();
        s.beginTransaction();
        BigDecimal tres = new BigDecimal(2);
        List list = juego.existeFicha(dniJugador);
        if (!(list.isEmpty())){
             Ficha f =(Ficha) list.get(0);
             f.setPuntos(f.getPuntos().add(tres));
             BigDecimal Valor1 = new BigDecimal(1);
             f.setInA2(f.getInA2().add(Valor1)); 
             s.update(f);
             s.getTransaction().commit();
        }
         else{
                Ficha f = juego.creaFicha(dniJugador,equipo);
                f.setInA2(BigDecimal.ONE);
                f.setPuntos(tres);
                s.save(f);
                s.getTransaction().commit();     
         } 
        s.close();
        SumarPuntos(2);
        this.setVisible(false);
        
    }//GEN-LAST:event_aIn2BtnActionPerformed

    private void aOut2BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aOut2BtnActionPerformed
        // TODO add your handling code here:
         Session s = NewHibernateUtil.getSessionFactory().openSession();
        s.beginTransaction();
        List list = juego.existeFicha(dniJugador);
        if (!(list.isEmpty())){
             Ficha f =(Ficha) list.get(0);
             BigDecimal Valor1 = new BigDecimal(1);//creo un Big decimal que vale 1 para sumarle 1 a las asistencias existentes
             f.setOutA2(f.getOutA2().add(Valor1)); 
             s.update(f);
             s.getTransaction().commit();
        }
         else{
                Ficha f = juego.creaFicha(dniJugador,equipo);
                f.setOutA2(BigDecimal.ONE);
                s.save(f);
                s.getTransaction().commit();     
         } 
        s.close();
        this.setVisible(false);
    }//GEN-LAST:event_aOut2BtnActionPerformed

    private void bIn2BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bIn2BtnActionPerformed
        // TODO add your handling code here:
        Session s = NewHibernateUtil.getSessionFactory().openSession();
        s.beginTransaction();
        BigDecimal tres = new BigDecimal(2);
        List list = juego.existeFicha(dniJugador);
        if (!(list.isEmpty())){
             Ficha f =(Ficha) list.get(0);
             f.setPuntos(f.getPuntos().add(tres));
             BigDecimal Valor1 = new BigDecimal(1);//creo un Big decimal que vale 1 para sumarle 1 a las asistencias existentes
             f.setInB2(f.getInB2().add(Valor1)); 
             s.update(f);
             s.getTransaction().commit();
        }
         else{
                Ficha f = juego.creaFicha(dniJugador,equipo);
                f.setInB2(BigDecimal.ONE);
                f.setPuntos(tres);
                s.save(f);
                s.getTransaction().commit();     
         } 
        s.close();
        SumarPuntos(2);
        this.setVisible(false);
        
    }//GEN-LAST:event_bIn2BtnActionPerformed

    private void cInOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cInOutBtnActionPerformed
        // TODO add your handling code here:
           Session s = NewHibernateUtil.getSessionFactory().openSession();
        s.beginTransaction();
        BigDecimal tres = new BigDecimal(2);
        List list = juego.existeFicha(dniJugador);
        if (!(list.isEmpty())){
             Ficha f =(Ficha) list.get(0);
             f.setPuntos(f.getPuntos().add(tres));
             BigDecimal Valor1 = new BigDecimal(1);//creo un Big decimal que vale 1 para sumarle 1 a las asistencias existentes
             f.setInC2(f.getInC2().add(Valor1)); 
             s.update(f);
             s.getTransaction().commit();
        }
         else{
                Ficha f = juego.creaFicha(dniJugador,equipo);
                f.setInC2(BigDecimal.ONE);
                f.setPuntos(tres);
                s.save(f);
                s.getTransaction().commit();     
         } 
        s.close();
        SumarPuntos(2);
        this.setVisible(false);
    }//GEN-LAST:event_cInOutBtnActionPerformed

    private void cOut2btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cOut2btnActionPerformed
        // TODO add your handling code here:
        Session s = NewHibernateUtil.getSessionFactory().openSession();
        s.beginTransaction();
        List list = juego.existeFicha(dniJugador);
        if (!(list.isEmpty())){
             Ficha f =(Ficha) list.get(0);
             BigDecimal Valor1 = new BigDecimal(1);//creo un Big decimal que vale 1 para sumarle 1 a las asistencias existentes
             f.setOutC2(f.getOutC2().add(Valor1)); 
             s.update(f);
             s.getTransaction().commit();
        }
         else{
                Ficha f = juego.creaFicha(dniJugador,equipo);
                f.setOutC2(BigDecimal.ONE);
                s.save(f);
                s.getTransaction().commit();     
         } 
        s.close();
        this.setVisible(false);
    }//GEN-LAST:event_cOut2btnActionPerformed

    private void d2InBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d2InBtnActionPerformed
        // TODO add your handling code here:
        Session s = NewHibernateUtil.getSessionFactory().openSession();
        s.beginTransaction();
        BigDecimal tres = new BigDecimal(2);
        List list = juego.existeFicha(dniJugador);
        if (!(list.isEmpty())){
             Ficha f =(Ficha) list.get(0);
             f.setPuntos(f.getPuntos().add(tres));
             BigDecimal Valor1 = new BigDecimal(1);//creo un Big decimal que vale 1 para sumarle 1 a las asistencias existentes
             f.setInD2(f.getInD2().add(Valor1)); 
             s.update(f);
             s.getTransaction().commit();
        }
         else{
                Ficha f = juego.creaFicha(dniJugador,equipo);
                f.setInD2(BigDecimal.ONE);
                f.setPuntos(tres);
                s.save(f);
                s.getTransaction().commit();     
         } 
        s.close();
        SumarPuntos(2);
        this.setVisible(false);
    }//GEN-LAST:event_d2InBtnActionPerformed

    private void libreOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_libreOutActionPerformed
        // TODO add your handling code here:
         Session s = NewHibernateUtil.getSessionFactory().openSession();
        s.beginTransaction();
        List list = juego.existeFicha(dniJugador);
        if (!(list.isEmpty())){
             Ficha f =(Ficha) list.get(0);
             BigDecimal Valor1 = new BigDecimal(1);//creo un Big decimal que vale 1 para sumarle 1 a las asistencias existentes
             f.setOutLibres(f.getOutLibres().add(Valor1)); 
             s.update(f);
             s.getTransaction().commit();
        }
         else{
                Ficha f = juego.creaFicha(dniJugador,equipo);
                f.setOutLibres(BigDecimal.ONE);
                s.save(f);
                s.getTransaction().commit();     
         } 
        s.close();
        this.setVisible(false);
    }//GEN-LAST:event_libreOutActionPerformed

    private void libreInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_libreInActionPerformed
        // TODO add your handling code here:
         Session s = NewHibernateUtil.getSessionFactory().openSession();
        s.beginTransaction();
        BigDecimal tres = new BigDecimal(1);
        List list = juego.existeFicha(dniJugador);
        if (!(list.isEmpty())){
             Ficha f =(Ficha) list.get(0);
             f.setPuntos(f.getPuntos().add(tres));
             BigDecimal Valor1 = new BigDecimal(1);//creo un Big decimal que vale 1 para sumarle 1 a las asistencias existentes
             f.setInLibres(f.getInLibres().add(Valor1)); 
             s.update(f);
             s.getTransaction().commit();
        }
         else{
                Ficha f = juego.creaFicha(dniJugador,equipo);
                f.setInLibres(BigDecimal.ONE);
                f.setPuntos(tres);
                s.save(f);
                s.getTransaction().commit();     
         } 
        s.close();
        SumarPuntos(1);
        this.setVisible(false);
    }//GEN-LAST:event_libreInActionPerformed

    private void f_inBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_inBtnActionPerformed
        // TODO add your handling code here:
        Session s = NewHibernateUtil.getSessionFactory().openSession();
        s.beginTransaction();
        BigDecimal tres = new BigDecimal(2);
        List list = juego.existeFicha(dniJugador);
        if (!(list.isEmpty())){
             Ficha f =(Ficha) list.get(0);
             f.setPuntos(f.getPuntos().add(tres));
             BigDecimal Valor1 = new BigDecimal(1);//creo un Big decimal que vale 1 para sumarle 1 a las asistencias existentes
             f.setInF(f.getInF().add(Valor1)); 
             s.update(f);
             s.getTransaction().commit();
        }
         else{
                Ficha f = juego.creaFicha(dniJugador,equipo);
                f.setInF(BigDecimal.ONE);
                f.setPuntos(tres);
                s.save(f);
                s.getTransaction().commit();     
         } 
        s.close();
        SumarPuntos(2);
        this.setVisible(false);
    }//GEN-LAST:event_f_inBtnActionPerformed

    private void f_OutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_OutBtnActionPerformed
        // TODO add your handling code here:
        Session s = NewHibernateUtil.getSessionFactory().openSession();
        s.beginTransaction();
        List list = juego.existeFicha(dniJugador);
        if (!(list.isEmpty())){
             Ficha f =(Ficha) list.get(0);
             BigDecimal Valor1 = new BigDecimal(1);//creo un Big decimal que vale 1 para sumarle 1 a las asistencias existentes
             f.setOutF(f.getOutF().add(Valor1)); 
             s.update(f);
             s.getTransaction().commit();
        }
         else{
                Ficha f = juego.creaFicha(dniJugador,equipo);
                f.setOutF(BigDecimal.ONE);
                s.save(f);
                s.getTransaction().commit();     
         } 
        s.close();
        this.setVisible(false);
    }//GEN-LAST:event_f_OutBtnActionPerformed
   
    public void SumarPuntos(int puntos){
        if (equipo.equals((String)partido.getLocal()))
            partido.sumarPuntosLocal(puntos);
        else
            partido.sumarPuntosVisit(puntos);
    }
    
    
    
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CartaDeTiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CartaDeTiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CartaDeTiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CartaDeTiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CartaDeTiro().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aIn2Btn;
    private javax.swing.JButton aIn3Btn;
    private javax.swing.JButton aOut2Btn;
    private javax.swing.JButton aOut3Btn;
    private javax.swing.JButton bIn2Btn;
    private javax.swing.JButton bIn3btn;
    private javax.swing.JButton bOut2Btn;
    private javax.swing.JButton bOut3Btn;
    private javax.swing.JButton cIn3Btn;
    private javax.swing.JButton cInOutBtn;
    private javax.swing.JButton cOut2btn;
    private javax.swing.JButton cOut3Btn;
    private javax.swing.JButton d2InBtn;
    private javax.swing.JButton dIn3Btn;
    private javax.swing.JButton dOut2Btn;
    private javax.swing.JButton dOut3Btn;
    private javax.swing.JButton eIn2Btn;
    private javax.swing.JButton eIn3Btn;
    private javax.swing.JButton eOut2Btn;
    private javax.swing.JButton eOut3Btn;
    private javax.swing.JButton f_OutBtn;
    private javax.swing.JButton f_inBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton libreIn;
    private javax.swing.JButton libreOut;
    // End of variables declaration//GEN-END:variables
}
