
import java.awt.PopupMenu;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JMenuItem;
import obj.Equipo;
import obj.Ficha;
//import obj.Filtro;
import obj.Jugador;
import org.hibernate.Criteria;
import org.hibernate.Session;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author nicol
 */
public class Estadistica extends javax.swing.JFrame {
    private ArrayList<Jugador> jugadores =  new ArrayList();
    Filtro f = null;
    protected int cantPartidos = 0;
    /**
     * Creates new form Estadistica
     */
    public Estadistica() {
        initComponents();
        cargaJugadores();
        setSize(420, 350);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setTitle("generar estadisticas");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu1 = new java.awt.PopupMenu();
        jButton1 = new javax.swing.JButton();
        filtrarBtn = new javax.swing.JButton();
        cantPartBtn = new javax.swing.JButton();
        CondicionBtn = new javax.swing.JButton();
        comboJugadores = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        volverBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        popupMenu1.setLabel("popupMenu1");

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(null);

        filtrarBtn.setText("filtrar");
        filtrarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtrarBtnActionPerformed(evt);
            }
        });
        getContentPane().add(filtrarBtn);
        filtrarBtn.setBounds(150, 245, 59, 20);

        cantPartBtn.setText("Cantidad de partidos");
        cantPartBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantPartBtnActionPerformed(evt);
            }
        });
        getContentPane().add(cantPartBtn);
        cantPartBtn.setBounds(10, 110, 170, 20);

        CondicionBtn.setText("Condicion");
        CondicionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CondicionBtnActionPerformed(evt);
            }
        });
        getContentPane().add(CondicionBtn);
        CondicionBtn.setBounds(140, 160, 100, 23);

        comboJugadores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jugador" }));
        getContentPane().add(comboJugadores);
        comboJugadores.setBounds(150, 10, 100, 20);

        jButton2.setText("Rival");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(260, 110, 55, 23);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/info-caja-azul-icono-5732-32.png"))); // NOI18N
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(380, 10, 40, 41);

        volverBtn.setText("volver");
        volverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBtnActionPerformed(evt);
            }
        });
        getContentPane().add(volverBtn);
        volverBtn.setBounds(350, 290, 63, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/barras.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 420, 320);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void filtrarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtrarBtnActionPerformed
      /* String seleccionado= (String) comboJugadores.getSelectedItem();
       int inicio = seleccionado.indexOf("(");
       int fin = seleccionado.lastIndexOf(")");
       String dniJugador = seleccionado.substring(inicio+1, fin);
       System.out.println(dniJugador);
       CantPartidos filtro = new CantPartidos();
       setCantPartidos();
       filtro.setCantPartidos(cantPartidos);
       filtro.setDniJugador(dniJugador);*/
       f.setFichas();
       TablaEstadistica tabla = new TablaEstadistica();
       List<Ficha> fichas =  f.filtrar();
        System.out.println("el tamaño de la lista es de "+fichas.size());
       tabla.setFichas(fichas);
       tabla.cargaDatos();
       tabla.setVisible(true);
    }//GEN-LAST:event_filtrarBtnActionPerformed

    private void cantPartBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantPartBtnActionPerformed
        // TODO add your handling code here:
       
       String dniJugador = getJugadorSeleccionado();
       NumeroDePartidos partidos = new NumeroDePartidos();
       partidos.setEstadistica(this);
       partidos.setDniJugador(dniJugador);
       partidos.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_cantPartBtnActionPerformed

    private void CondicionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CondicionBtnActionPerformed
        // TODO add your handling code here:
       String dniJugador = getJugadorSeleccionado();
       CondicionView cond = new CondicionView();
       cond.setEstadistica(this);
       cond.setDniJugador(dniJugador);
       cond.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_CondicionBtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        RivalView vista = new RivalView();
        vista.setDni(getJugadorSeleccionado());
        vista.setEstadistica(this);
        vista.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Informacion info = new Informacion();
        info.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void volverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverBtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_volverBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public String getJugadorSeleccionado(){
       String seleccionado= (String) comboJugadores.getSelectedItem();
       int inicio = seleccionado.indexOf("(");
       int fin = seleccionado.lastIndexOf(")");
       String dniJugador = seleccionado.substring(inicio+1, fin);
       System.out.println(dniJugador);
       return dniJugador;
    }
   
    public void filtrarGeneral(String dniJugador){
        
    }
        
    
    
    
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Estadistica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Estadistica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Estadistica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Estadistica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Estadistica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CondicionBtn;
    private javax.swing.JButton cantPartBtn;
    private javax.swing.JComboBox<String> comboJugadores;
    private javax.swing.JButton filtrarBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private java.awt.PopupMenu popupMenu1;
    private javax.swing.JButton volverBtn;
    // End of variables declaration//GEN-END:variables

    private void cargaJugadores() {
        Session s = NewHibernateUtil.getSessionFactory().openSession();
        s.beginTransaction();
        Criteria criteria = s.createCriteria(Jugador.class);
        jugadores = (ArrayList<Jugador>) criteria.list();
        
        for(Jugador j:jugadores){
            comboJugadores.addItem(j.toString());  
        }
         s.getTransaction().commit();
        s.close();
    }
    public boolean existeFiltro(){
        if (f != null)
            return true;
        else 
            return false;
    }
    public Filtro getFiltro(){
        return f;
    }
    public void setFiltro(Filtro f){
        this.f = f;
    }
}
