/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.List;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import obj.Jugador;
import obj.Equipo;
import obj.EquipoId;
import javax.swing.JComboBox;
import org.hibernate.Criteria;
import org.hibernate.Session;


/**
 *
 * @author nicol
 */
public class newJugView extends javax.swing.JFrame {

    /**
     * Creates new form newJugView
     */
    private ArrayList<Equipo> equipos =  new ArrayList();
    private Inicio inicio;
     
    public newJugView() {
        initComponents();
        setSize(453,398);
        this.setTitle("Nuevo Jugador");
        setLocationRelativeTo(null);
        setLocationRelativeTo(this);
        cargarEquipos();
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboEquipos = new javax.swing.JComboBox<>();
        textNombre = new javax.swing.JTextField();
        textApellido = new javax.swing.JTextField();
        textDni = new javax.swing.JTextField();
        textPos = new javax.swing.JTextField();
        textDorsal = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        buttAjugador = new javax.swing.JButton();
        buttVolver = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        comboEquipos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "seleccionar equipo" }));
        comboEquipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboEquiposActionPerformed(evt);
            }
        });
        getContentPane().add(comboEquipos);
        comboEquipos.setBounds(130, 150, 141, 22);

        textNombre.setBackground(new java.awt.Color(153, 153, 153));
        textNombre.setToolTipText("");
        textNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNombreActionPerformed(evt);
            }
        });
        getContentPane().add(textNombre);
        textNombre.setBounds(110, 60, 83, 22);

        textApellido.setBackground(new java.awt.Color(153, 153, 153));
        textApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textApellidoActionPerformed(evt);
            }
        });
        getContentPane().add(textApellido);
        textApellido.setBounds(290, 60, 83, 22);

        textDni.setBackground(new java.awt.Color(153, 153, 153));
        getContentPane().add(textDni);
        textDni.setBounds(180, 110, 77, 22);

        textPos.setBackground(new java.awt.Color(153, 153, 153));
        getContentPane().add(textPos);
        textPos.setBounds(160, 220, 77, 22);

        textDorsal.setBackground(new java.awt.Color(153, 153, 153));
        getContentPane().add(textDorsal);
        textDorsal.setBounds(160, 270, 77, 22);

        jLabel1.setText("nombre");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 60, 44, 16);

        jLabel2.setText("apellido");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(230, 60, 44, 16);

        jLabel3.setText("dni");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(140, 110, 17, 16);

        jLabel4.setText("pos");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(110, 220, 40, 16);

        jLabel5.setText("dorsal");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(110, 270, 35, 16);

        buttAjugador.setText("Agregar Jugador");
        buttAjugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttAjugadorActionPerformed(evt);
            }
        });
        getContentPane().add(buttAjugador);
        buttAjugador.setBounds(70, 330, 300, 30);

        buttVolver.setText("volver");
        buttVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttVolverActionPerformed(evt);
            }
        });
        getContentPane().add(buttVolver);
        buttVolver.setBounds(380, 0, 67, 25);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tablaplanilla_1.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 450, 380);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboEquiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboEquiposActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_comboEquiposActionPerformed
    public void setInicio(Inicio inicio){
        this.inicio = inicio;
    }
    private void textNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNombreActionPerformed

    private void textApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textApellidoActionPerformed

    private void buttAjugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttAjugadorActionPerformed
        // TODO add your handling code here:
        String equipo;
        equipo = (String) comboEquipos.getSelectedItem();
        Session s = NewHibernateUtil.getSessionFactory().openSession();
        s.beginTransaction();
        Jugador nuevo = new Jugador (new BigDecimal(textDni.getText()));
        nuevo.setApellido(textApellido.getText());
        nuevo.setDorsal(textDorsal.getText());
        nuevo.setNombre(textNombre.getText());
        nuevo.setPos(textPos.getText());
        
        for(Equipo e: equipos){
            if(e.toString().equals(equipo)){
                nuevo.setEquipo(e);
            }
        }
        s.save(nuevo);
        s.getTransaction().commit();
        s.close();
        
        MensajeJugador mensaje = new MensajeJugador();
        mensaje.setInicio(inicio);
        mensaje.setVisible(true);
        this.setVisible(false);
       
   
        
        
        
    }//GEN-LAST:event_buttAjugadorActionPerformed

    private void buttVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttVolverActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        inicio.setVisible(true);
    }//GEN-LAST:event_buttVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newJugView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newJugView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newJugView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newJugView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newJugView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttAjugador;
    private javax.swing.JButton buttVolver;
    private javax.swing.JComboBox<String> comboEquipos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField textApellido;
    private javax.swing.JTextField textDni;
    private javax.swing.JTextField textDorsal;
    private javax.swing.JTextField textNombre;
    private javax.swing.JTextField textPos;
    // End of variables declaration//GEN-END:variables

    private void cargarEquipos() {
         Session s = NewHibernateUtil.getSessionFactory().openSession();
        s.beginTransaction();
        Criteria criteria = s.createCriteria(Equipo.class);
        equipos = (ArrayList<Equipo>) criteria.list();
        
        for(Equipo e:equipos){
            comboEquipos.addItem(e.toString());  
        }
         s.getTransaction().commit();
        s.close();
    }
    
    
}
