
import java.util.ArrayList;
import obj.Equipo;
import org.hibernate.Criteria;
import org.hibernate.Session;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author nicol
 */
public class NuevoPartidoView extends javax.swing.JFrame {

    /**
     * Creates new form NuevoPartido
     */
    private ArrayList<Equipo> equipos =  new ArrayList();
    private Inicio inicio;
    public NuevoPartidoView() {
        initComponents();
        setSize(480,342);
        setLocationRelativeTo(null);
        cargarEquipos();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        cbLocal = new javax.swing.JComboBox<>();
        cbVisitante = new javax.swing.JComboBox<>();
        btnIniciarPartido = new javax.swing.JButton();
        buttVolver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        cbLocal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "local" }));
        getContentPane().add(cbLocal);
        cbLocal.setBounds(20, 150, 80, 22);

        cbVisitante.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "visitante" }));
        getContentPane().add(cbVisitante);
        cbVisitante.setBounds(310, 150, 110, 22);

        btnIniciarPartido.setText("Iniciar Partido");
        btnIniciarPartido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarPartidoActionPerformed(evt);
            }
        });
        getContentPane().add(btnIniciarPartido);
        btnIniciarPartido.setBounds(170, 260, 111, 25);

        buttVolver.setText("volver");
        buttVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttVolverActionPerformed(evt);
            }
        });
        getContentPane().add(buttVolver);
        buttVolver.setBounds(410, 10, 67, 25);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/localvisita.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-30, 0, 510, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarPartidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarPartidoActionPerformed
        // TODO add your handling code here:
        String local = (String) cbLocal.getSelectedItem();
        String visitante =(String) cbVisitante.getSelectedItem();
        Equipo equipoLocal = new Equipo();
        Equipo equipoVisitante = new Equipo();
        for(Equipo e : equipos){
            
            if (e.toString().equals(local))
                 equipoLocal = e;
                 
            else
                if (e.toString().equals(visitante))
                    equipoVisitante=e;
        }
        System.out.println(equipoLocal.getId().getNombre());
        System.out.println(equipoVisitante.getId().getNombre());
        EnJuego partido = new EnJuego(equipoLocal,equipoVisitante);
        partido.setVisible(true);
    }//GEN-LAST:event_btnIniciarPartidoActionPerformed
    public void setInicio(Inicio inicio){
        this.inicio = inicio;
    }
    private void buttVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttVolverActionPerformed
        // TODO add your handling code here:
        inicio.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_buttVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoPartidoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoPartidoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoPartidoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoPartidoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevoPartidoView().setVisible(true);
            }
        });
    }
    
    private void cargarEquipos() {
         Session s = NewHibernateUtil.getSessionFactory().openSession();
        s.beginTransaction();
        Criteria criteria = s.createCriteria(Equipo.class);
        equipos = (ArrayList<Equipo>) criteria.list();
        
        for(Equipo e:equipos){
            cbLocal.addItem(e.toString());
            cbVisitante.addItem(e.toString());
        }
         s.getTransaction().commit();
        s.close();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciarPartido;
    private javax.swing.JButton buttVolver;
    private javax.swing.JComboBox<String> cbLocal;
    private javax.swing.JComboBox<String> cbVisitante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
