
import java.util.List;
import obj.Ficha;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author nicol
 */
public class NumeroDePartidos extends javax.swing.JFrame {
     private int cantPartidos;
     private Estadistica estadistica;
     private String dniJugador;
    /**
     * Creates new form NumeroDePartidos
     */
    public NumeroDePartidos() {
        initComponents();
        this.setLocationRelativeTo(null);
        setSize(300, 250);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(150, 150));
        getContentPane().setLayout(null);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "cantidad de partidos", "1", "3", "5", "10" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(80, 70, 151, 22);

        jButton1.setText("Aplicar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(110, 120, 71, 25);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/INICIO.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 300, 250);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       CantPartidos filtro = new CantPartidos();
       setCantPartidos();
       filtro.setCantPartidos(cantPartidos);
       filtro.setDniJugador(dniJugador);
       //TablaEstadistica tabla = new TablaEstadistica();
       //List<Ficha> fichas =  filtro.filtrar();
       //tabla.setFichas(fichas);
       //tabla.cargaDatos();
       //tabla.setVisible(true);
       if(estadistica.existeFiltro()){
           filtroAnd fAnd = new filtroAnd(estadistica.getFiltro(),filtro);
           System.out.println("entre a filtro cant partidos and");
           estadistica.setFiltro(fAnd);
       }
       else{
           estadistica.setFiltro(filtro);
           filtro.setFichas();
           System.out.println("entre a filtro cant partidos simple");
          
       }
       estadistica.setVisible(true);
       this.setVisible(false);
 
           
    }//GEN-LAST:event_jButton1ActionPerformed
    
    public void setEstadistica(Estadistica estadistica){
        this.estadistica = estadistica;
    }
    public void setDniJugador(String dniJugador){
        this.dniJugador = dniJugador;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NumeroDePartidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NumeroDePartidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NumeroDePartidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NumeroDePartidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NumeroDePartidos().setVisible(true);
            }
        });
    }
     private void setCantPartidos() {
        int lugar=jComboBox1.getSelectedIndex();
        if (lugar == 1)
            cantPartidos = 1;
        if (lugar == 2)
            cantPartidos=3;
        if (lugar == 3)
            cantPartidos=5;
        if (lugar == 4)
            cantPartidos=10;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
