
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import obj.Calculadora;
import obj.Ficha;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author nicol
 */
public class TablaEstadistica extends javax.swing.JFrame {

    
    protected List<Ficha> fichas;
    /**
     * Creates new form TablaEstadistica
     */
    public TablaEstadistica() {
        initComponents();
         this.setLocationRelativeTo(null);
         
    setSize(1400, 300);
  
        
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaFicha = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 51));
        getContentPane().setLayout(null);

        tablaFicha.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "puntos", "%puntos", "%triplesA", "%triplesB", "%triplesC", "%triplesD", "%triplesE", "%puntosF", "%doblesA", "%doblesB", "%doblesC", "%doblesD", "%doblesE", "asistenciasXpartido", "robosXpartido", "rebDefXpartido", "rebOfXpartido", "rebotesXpartido", "taponesXpartido"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaFicha);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 40, 1400, 120);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/INICIO.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(1, -4, 1400, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TablaEstadistica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TablaEstadistica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TablaEstadistica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TablaEstadistica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TablaEstadistica().setVisible(true);
            }
        });
    }
    
    
    
    
    public void setFichas(List<Ficha> fichas){
        this.fichas= fichas;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaFicha;
    // End of variables declaration//GEN-END:variables

    public void cargaDatos() {
        Calculadora c = new Calculadora(fichas);
        System.out.println(fichas.size());
        DefaultTableModel tModelFichas = (DefaultTableModel) tablaFicha.getModel();
        tModelFichas.setRowCount(0);
        String datos[] = new String[31];
        datos[0] = fichas.get(0).getJugador().toString();
        datos[1] = Float.toString(c.getPuntos());
        datos[2] = Float.toString(c.getPuntosXPartido());
        datos[3] = Float.toString(c.getPorcentajeTriplesA());
        datos[4] = Float.toString(c.getPorcentajeTriplesb());
        datos[5]  =Float.toString(c.getPorcentajeTriplesC());
        datos[6]  =Float.toString(c.getPorcentajeTriplesD());
        datos[7]  =Float.toString(c.getPorcentajeTriplesE());
        datos[8]  =Float.toString(c.getPorcentajeF());
        datos[9]  =Float.toString(c.getPorcentajeDoblesA());
        datos[10]  =Float.toString(c.getPorcentajeDoblesB());
        datos[11]  =Float.toString(c.getPorcentajeDoblesC());
        datos[12]  =Float.toString(c.getPorcentajeDoblesD());
        datos[13]  =Float.toString(c.getPorcentajeDoblesE());
        datos[14]  =Float.toString(c.getAsistenciasXPartido());
        datos[15]  =Float.toString(c.robosXPartido());
        datos[16]  =Float.toString(c.rebotesDefXPartido());
        datos[17]  =Float.toString(c.rebotesOffXpartido());
        datos[18]  =Float.toString(c.rebotesXPartido());
        datos[19]  =Float.toString(c.tapasXPartido());
        tModelFichas.addRow(datos);
       
    
    }
    public void addFichas(List<Ficha> fichitas){
        fichas.addAll(fichitas);
    }
    public JTable getJtable(){
        return tablaFicha;
    }
    public List<Ficha> getFichas(){
        return fichas;
    }
}
